// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzsCTD9QKIfH9rXnDpYGs7luxqMXnTts',
    appId: '1:478607183864:android:280e1091fdd3e53fe1d00d',
    messagingSenderId: '478607183864',
    projectId: 'announdo-9090',
    storageBucket: 'announdo-9090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE5crVOAK88bLari8zYlnZB56y8IKJCYg',
    appId: '1:478607183864:ios:8de36a7a86ec3ef2e1d00d',
    messagingSenderId: '478607183864',
    projectId: 'announdo-9090',
    storageBucket: 'announdo-9090.appspot.com',
    iosClientId: '478607183864-bsld8fc4fdq1bbtinj4bdu8rmonoh47t.apps.googleusercontent.com',
    iosBundleId: 'com.announdo.announdo',
  );
}
